feature/num_channels
gnuradio/SigMF pull request #138
Opened 2021-06-19 07:05 UTC by Teque5

@ke8ctn @jacobagilbert 

### Features 
- Closes #133 allowing multiple interleaved channels in a single dataset file.
- `core:num_channels` key to spec with relevant tests.
- Now allow reading all samples in a simpler way similar to numpy. See new example at top of `README.md`.

### Uncertainty
- In the `read_samples()` method of `SigMFFile` there is an option to read `raw_components`. I'm not sure of the intent of this option, but my interpretation is that it should also ignore the interleaving. See my updated documentation for this method.
- If this gets merged it should probably increment the spec. I didn't change it here.

_ps: This took 3 avengers movies to complete._

2021-07-01 01:27 UTC, bhilburn requested changes
Overall looks good to me.

In addition to adding the field in `global`, I think there needs to be some additional description of how that field works later in the spec. Namely, under the `## Dataset Format` heading, I think we should add additional copy under this section explaining the new field:

```md
Complex samples should be interleaved, with the in-phase component first (i.e.,
`I[0]` `Q[0]` `I[1]` `Q[1]` ... `I[n]` `Q[n]`).  Also note that the `type`
applies to not only the real but also the imaginary component of a complex
sample.
```

First pass on addition:

```md
Where `core:num_channels` in the `global` object indicates that the recording 
contains more than one channel, samples from those channels should be 
interleaved in the same manner, with the same index from each channel's 
sample serially in the recording. For example, a recording with two channels 
of `i16_le` representing real-valued stereo data from an oscilloscope, and so 
here labeled `L` for `left` and `R` for `right, the data should appear 
as `L[0]` `R[0]` `L[1]` `R[1]` ... `L[n]` `R[n]`.
```

Thoughts? It feels a bit tricky to explain super clearly here in text.

Also, FWIW, you can drop the line assigning copyright to GRF in future code. You can either retain copyright as original author (or org, like Aerospace), or omit entirely. GNU Radio no longer assigns copyright to FSF.

2021-07-01 17:14 UTC, jacobagilbert commented
I agree @bhilburn - these can probably be combined into one coherent statement:

```
Complex samples should be interleaved, with the in-phase component first (i.e.,
`I[0]` `Q[0]` `I[1]` `Q[1]` ... `I[n]` `Q[n]`). When `core:num_channels` in the
`global` object indicates that the recording contains more than one channel,
samples from those channels should be interleaved in the same manner, with
the same index from each channel's sample serially in the recording. For example,
a recording with two channels of `i16_le` representing real-valued stereo data
from an oscilloscope, and so here labeled `L` for `left` and `R` for `right, the
data should appear as `L[0]` `R[0]` `L[1]` `R[1]` ... `L[n]` `R[n]`. The data type
specified by `core:data_type` applies to all channels of data.
```

2021-07-02 19:41 UTC, Teque5 commented
@bhilburn @jacobagilbert I added the text mostly as you suggested. I think this is ready to merge.

I didn't see the line about assigning copyright to GRF. If you point it out I could remove it.

2021-07-02 21:40 UTC, ke8ctn commented on sigmf/sigmffile.py
> +            if file_size % sample_count != 0:
This seems wrong. `file_size` and `sample_size` are both in bytes, so `file_size % sample_size == 0` iff the file contains a whole number of samples (single channel), but `file_size % sample_count` doesn't work the same way. As a simple example, consider what happens when `file_size == sample_size + 1` (for `sample_size > 1`).

To generalize for multiple channels, I think the condition should just be `file_size % (sample_size * num_channels) != 0`.

2021-07-03 00:53 UTC, Teque5 commented
Latest push resolves @ke8ctn's concern.

2021-07-15 01:33 UTC, bhilburn commented
Looks like I merged in the wrong order 😂

@Teque5 - Your language looks great to me. Two things preventing merge:

1) We've got conflicts on this PR now against master, and
2) The GRF copyright assignment in this branch is in `error.py`. See this changeset:

<img width="563" alt="Screenshot 2021-07-14 213239" src="https://user-images.githubusercontent.com/569571/125713972-e2edc937-0d1a-4ebd-9c99-dd737ac505f5.png">

Once resolved, this is an immediate merge 🙂

2021-07-15 03:43 UTC, Teque5 commented
Okay this branch is now ready to merge. It should be done **before** the feature/logo branch (#143).

2021-07-28 17:04 UTC, merged

2021-07-28 17:45 UTC, Teque5 commented
Great. Now that this is in I think the next priority is to submit a pr to [cusignal](https://github.com/rapidsai/cusignal) and [gr-sigmf](https://github.com/skysafe/gr-sigmf) to accept `num_channels`.